=== kartoza/qgis_checklist_checker/schemas/checklist-check.json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "$id": "https://kartoza.github.io/qgis_dataset_qa_workbench/schema.json",
  "type": "object",
  "title": "Schema for checklist definition files for the QGIS Dataset QA Workbench plugin",
  "description": "This schema can be used to validate new checklists created for using with the QGIS Dataset QA Workbench plugin",
  "properties": {
    "name": {
      "type": "string",
      "title": "Name of the checklist",
      "description": "Identifier used for the checklist in the QGIS UI"
    },
    "description": {
      "type": "string",
      "title": "Description of the checklist",
      "description": "A short text explaining what the current checklist is about"
    },
    "dataset_type": {
      "type": "string",
      "title": "Type of dataset being validated",
      "description": "The type of dataset that this checklist operates on",
      "enum": [
        "document",
        "raster",
        "vector"
      ]
    },
    "validation_artifact_type": {
      "type": "string",
      "title": "Artifact type being validated",
      "description": "The type of artifact that this checklist operates on",
      "enum": [
        "dataset",
        "metadata",
        "style"
      ]
    },
    "checks": {
      "type": "array",
      "title": "Checklist checks",
      "description": "A list of checks that are part of this checlist",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name of this check",
            "description": "Name of this check in the checklist"
          },
          "description": {
            "type": "string",
            "title": "Check description",
            "description": "Small text explaining what this check is about"
          },
          "guide": {
            "type": "string",
            "title": "Check operation guide",
            "description": "Small text specifying how a human operator might go ahead and validate this check"
          },
          "automation": {
            "type": "object",
            "title": "Automation configuration for this check",
            "description": "Configuration for the automated execution of this validation check",
            "properties": {
              "algorithm_id": {
                "type": "string",
                "title": "Processing identifier of the algorithm",
                "description": "Identifier of the QGIS processing algorithm used to perform automation",
                "examples": ["qgis:checkvalidity"],
                "pattern": "^[a-z_-]+:[a-z_-]+$"
              },
              "artifact_parameter_name": {
                "type": "string",
                "title": "Name for the algorithm parameter that specifies the artifact being validated",
                "description": "Name of the algorithm parameter that specifies which of the algorithm's parameters represents the artifact currently being validated",
                "examples": ["INPUT_LAYER"]
              },
              "output_name": {
                "type": "string",
                "title": "Name of the algorithm parameter output where the result of this check will be gotten from",
                "description": "Name of the algorithm parameter that specifies which one of the algorithm's outputs holds the result of the validation.",
                "examples": ["INVALID_COUNT"]
              },
              "negate_output": {
                "type": "boolean",
                "title": "Whether to interpret a FALSE result from the processing algorithm as successful validation",
                "description": "Whether to interpret a result of FALSE coming from the processing algorithm as a sign of success in the validation"
              },
              "extra_parameters": {
                "type": "object",
                "title": "Any additional parameters necessary for running the processing algorithm",
                "description": "Any additional parameters necessary for running the processing algorithm"
              }
            },
            "required": [
              "algorithm_id"
            ]
          }
        },
        "required": [
          "name",
          "description",
          "guide"
        ]
      }
    },
    "report": {
      "type": "object",
      "title": "Handler for any post-validation actions",
      "description": "Configuration for doing post-validation actions with the generated validation report",
      "properties": {
        "algorithm_id": {
          "type": "string",
          "title": "Processing identifier of the report-handling algorithm",
          "description": "Identifier of the QGIS Processing algorithm used to handle the checklist's validation report"
        },
        "extra_parameters":{
          "type": "object",
          "title": "Any additional parameters necessary for running the post-validation algorithm",
          "description": "Any additional parameters necessary for running the post-validation algorithm"
        }
      },
      "required": [
        "algorithm_id"
      ]
    }
  },
  "required": [
    "name",
    "description",
    "dataset_type",
    "validation_artifact_type"
  ]
}

=== kartoza/qgis_checklist_checker/collections/dataset-qa-workbench-demo-checklists/checklists/document-style.json
{
  "name": "Sample checklist for validating styles",
  "description": "This is just a sample checklist - be sure to delete it",
  "dataset_type": "document",
  "validation_artifact_type": "style",
  "checks": [
    {
      "name": "style is identifiable",
      "description": "The style is identifiable",
      "guide": "Open the style file with an external text editor then look for the qgis/flags/Identifiable element. Check that its text equals '1'.",
      "automation": {
        "algorithm_id": "dataset_qa_workbench:qmlchecker",
        "artifact_parameter_name": "INPUT",
        "extra_parameters": {
          "INPUT_ITEMS_TO_CHECK": [
            "flags/Identifiable[.='1']"
          ]
        }
      }
    },
    {
      "name": "uses the SOVEREIGNT attribute to render symbology",
      "description": "The style document uses the QGIS QML style format",
      "guide": "Open the style file with an external text editor and then look to the qgis/renderer-v2 element. Check that its 'attr' attribute equals 'SOVEREIGNT'",
      "automation": {
        "algorithm_id": "dataset_qa_workbench:qmlchecker",
        "artifact_parameter_name": "INPUT",
        "extra_parameters": {
          "INPUT_ITEMS_TO_CHECK": [
            "renderer-v2[@attr='SOVEREIGNT']"
          ]
        }
      }
    }
  ]
}

=== kartoza/qgis_checklist_checker/collections/dataset-qa-workbench-demo-checklists/checklists/raster-dataset.json
{
  "name": "Sample checklist for raster layer I.",
  "description": "This is a sample checklist for raster layers.",
  "dataset_type": "raster",
  "validation_artifact_type": "dataset",
  "checks": [
    {
      "name": "CRS is EPSG:4326",
      "description": "Layer's Coordinate Reference System is lat-lon on WGS84 datum (i.e. EPSG code 4326)",
      "guide": "Open the layer properties dialog, then navigate to the 'Information' tab (should be the first one) and in the section called 'Information from provider' check if the 'CRS' field has a value of 'EPSG:4326 - WGS84 - Geographic'",
      "automation": {
        "algorithm_id": "dataset_qa_workbench:crschecker",
        "artifact_parameter_name": "INPUT_LAYER",
        "output_name": "OUTPUT",
        "extra_parameters": {
          "INPUT_CRS": "EPSG:4326"
        }
      }
    },
    {
      "name": "Extents cover region of interest",
      "description": "Layer's extent provides coverage of the whole region",
      "guide": "Open the layer properties dialog, then navigate to the 'Information' tab (should be the first one) and in the section named 'Information from provider' check if the value shown in the 'Extent' field covers the region of interest"
    },
    {
      "name": "Layer has 3 bands",
      "description": "Layer has the expected number of bands",
      "guide": "Open the layer properties dialog, then navigate to the 'Information' tab (should be the first one) and in the section named 'Bands' check if the value shown in the 'Band count' field is equal to 3"
    }
  ]
}

=== kartoza/qgis_checklist_checker/collections/dataset-qa-workbench-demo-checklists/checklists/vector-dataset-with-reportposter.json
{
  "name": "Sample checklist with report for posting to a remote server",
  "description": "This is just a sample checklist - be sure to delete it",
  "dataset_type": "vector",
  "validation_artifact_type": "dataset",
  "checks": [
    {
      "name": "geometry is valid",
      "description": "Layer's geometry does not have invalid geometries.",
      "guide": "Navigate to Vector -> Geometry tools -> Check Validity... and run the validity analysis tool. Afterwards check that there are no features on the `invalid output` layer",
      "automation": {
        "algorithm_id": "qgis:checkvalidity",
        "artifact_parameter_name": "INPUT_LAYER",
        "output_name": "INVALID_COUNT",
        "negate_output": true
      }
    },
    {
      "name": "CRS is EPSG:4326",
      "description": "Layer's Coordinate Reference System is lat-lon on WGS84 datum (i.e. EPSG code 4326)",
      "guide": "Open the layer properties dialog, then navigate to the 'information' tab (should be the first one) and in the section called 'Information from provider' check if the 'CRS' field has a value of 'EPSG:4326 - WGS84 - Geographic'",
      "automation": {
        "algorithm_id": "dataset_qa_workbench:crschecker",
        "artifact_parameter_name": "INPUT_LAYER",
        "output_name": "OUTPUT",
        "negate_output": false,
        "extra_parameters": {
          "INPUT_CRS": "EPSG:4326"
        }
      }
    }
  ],
  "report": {
    "algorithm_id": "dataset_qa_workbench:reportposter"
  }
}
